# Generated by Django 6.0.2 on 2026-02-18 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Technology, Business)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of category name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Source name (e.g., TechCrunch, The Verge)', max_length=200, unique=True)),
                ('url', models.URLField(help_text='Source URL or RSS feed URL', unique=True)),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('API', 'API Integration'), ('SCRAPER', 'Web Scraper')], default='RSS', help_text='How we fetch articles from this source', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this source is actively being fetched')),
                ('fetch_interval', models.IntegerField(default=60, help_text='How often to fetch (in minutes)')),
                ('last_fetched', models.DateTimeField(blank=True, help_text='When we last fetched articles from this source', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article headline', max_length=500)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=550, unique=True)),
                ('url', models.URLField(help_text='Original article URL', unique=True)),
                ('content', models.TextField(blank=True, help_text='Full article content (if fetched)')),
                ('summary', models.TextField(blank=True, help_text='Article summary or excerpt')),
                ('image_url', models.URLField(blank=True, help_text='Article featured image URL', null=True)),
                ('author', models.CharField(blank=True, help_text='Article author name', max_length=200)),
                ('published_at', models.DateTimeField(help_text='When the article was originally published')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='When we fetched this article')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Article category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category')),
                ('source', models.ForeignKey(help_text='Source this article came from', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.source')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'url'), name='unique_source_url')],
            },
        ),
    ]
